[package]
name = "lab3"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
csv = "1.3.1"
gtk = { version = "0.9.2", package = "gtk4", features = ["v4_6"] }
serde = { version = "1.0.216", features = ["derive"] }
